### ISSUE TITLE
Update Cinnamon...again

### ISSUE THREAD

**Issue by Yoshi2889** [Antergos/antergos-packages#140] opened 2016-11-20 12:06 UTC
Apparently not every Cinnamon package was updated and this is causing multiple issues ranging from crashes to random bugs. All cinnamon packages should be updated in Antergos or probably removed from the repo if they aren't altered by Antergos.

**Comment by lots0logs** [comment] 2016-11-20 12:14
Going to need more than that. All packages were updated so what specifically are you referring to?

**Comment by Yoshi2889** [comment] 2016-11-20 12:15
The cjs package is still version 3.0.1, for instance. I'm not sure if any more packages are out of date, but an IRC user fixed his system by using the Arch packages and that apparently resulted in a lot of upgrades.

**Comment by Yoshi2889** [comment] 2016-11-20 12:16
On further inspection cjs is 3.2.0 in this repo... The user never received 3.2.0 though, even after multiple repo resyncs.

**Comment by lots0logs** [comment] 2016-11-20 12:16
Not sure what that issue was actually caused by but like I said the packages were all updated. See: http://build.antergos.com/repo/antergos/packages/search/cjs

**Comment by karasu** [comment] 2016-11-20 12:56
I think there is a mirror (or some of them) that do not update as regularly as it should. But this is just a hunch, I have no proof.

**Comment by karasu** [comment] 2016-12-14 19:31
Well, cjs was rebuilt a long ago. @Yoshi2889 I suppose it is working for you as it is working here.

Closing.

**Closed by karasu** 2016-12-14 19:31 UTC
