### ISSUE TITLE
yaourt is broken

### ISSUE THREAD

**Issue by cookiengineer** [Antergos/antergos-packages#145] opened 2016-12-01 08:19 UTC
It seems as yaourt from the antergos/yaourt package is broken.

yaourt-1.8.1-1 behaves like this:

```bash
$ yaourt -Sy
:: Synchronizing package databases...
 antergos is up to date
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date

$ yaourt -Ss inox
community/faenza-icon-theme 1.3.1-4
    Icon theme designed for Equinox GTK theme
curl error: Couldn't resolve host name
```

And yaourt seems to not find any packages from AUR, only the ones from upstream Arch. How can I resolve this and fix it?

**Comment by lots0logs** [comment] 2016-12-01 10:33
I cannot reproduce the issue. It works fine for me. Try replacing your yaourtrc and makepkg.conf files with unmodified copies of those files.

**Comment by karasu** [comment] 2016-12-14 19:30
Well, obviously is not an antergos-packages problem. @cookiengineer I suggest you seek help in our forum (form.antergos.com)

Closing.

**Closed by karasu** 2016-12-14 19:30 UTC
