### ISSUE TITLE
Pamac 6.2.3 broken

### ISSUE THREAD

**Issue by EvanWashkow** [Antergos/antergos-packages#288] opened 2018-02-02 23:02 UTC
Just got the new update today, however, it is broken. I can open the application fine, however, I can't 1) refresh the package database or 2) install any packages (gets stuck "Checking inter-conflicts").

Please fix.

For now, I have reverted to 6.2.2 (command below if anyone else needs it).
`sudo pacman -U /var/cache/pacman/pkg/pamac-6.2.2-1-x86_64.pkg.tar.xz`

**Comment by EvanWashkow** [comment] 2018-02-02 23:19
I should clarify: it is version 6.2.3-2

**Comment by retro-wertz** [comment] 2018-02-03 01:39
i confirm this issue. sadly im on a new install, how to downgrade pamac?

**Comment by Xeers** [comment] 2018-02-03 01:45
This does not work correctly

**Comment by Palanthis** [comment] 2018-02-03 01:56
I can confirm that this issue is also happening on my MacBook running pure Arch and is repeatable in a VM, also running pure arch. So this is an upstream issue.

**Comment by EvanWashkow** [comment] 2018-02-03 06:39
@retro-wertz and for everyone who has this issue, but doesn’t have a cached version, I’ve uploaded it to my Google Drive, until it is fixed:

https://drive.google.com/open?id=11TJcbxSRoJd0KnmfMmU_aWMyMmYda78C

**Comment by Palanthis** [comment] 2018-02-03 06:41
Thanks! You rock!!

**Comment by EvanWashkow** [comment] 2018-02-03 06:42
Edited directory path. I forgot the extra `pkg/` on the end

**Comment by killajoe** [comment] 2018-02-03 06:49
it does not matter where you store it, more secure to store it under your ~/  !

**Comment by EvanWashkow** [comment] 2018-02-03 06:51
True. That would be better since the file ownership / permissions might not be properly set. Good catch.

**Comment by killajoe** [comment] 2018-02-03 06:55
`sudo su` is not needed too ;) one `sudo` should be good

**Comment by EvanWashkow** [comment] 2018-02-03 06:57
Good catch. Long week. I just copied it from my terminal window without thinking. Updated.

**Comment by EvanWashkow** [comment] 2018-02-03 06:57
I've reported this to Manjaro, since they are the package developers. AUR's build is also broken.

**Comment by LinxGem33** [comment] 2018-02-03 07:21
just to add for a workaround for other users who need a quick fix and have cleared their caches and until this issue is fixed you can install the dev version and i can confirm this solves the issue.
v6.2.2
```
sudo pacman -S pamac-dev
```
```
1 antergos/pamac 6.2.3-2 [installed]
    A GTK3 frontend for libalpm
2 antergos/pamac-dev v6.2.2.git+692-1
    A GTK3 frontend for libalpm
```

**Comment by philmmanjaro** [comment] 2018-02-03 12:45
The issue is not with **pamac** but with **vala 0.38.6**. Compiling it with **0.38.5** it works. We are currently checking why that is and provide a fix for this vala regression soon.

**Comment by philmmanjaro** [comment] 2018-02-03 16:39
Here is the needed fix for this problem: https://github.com/manjaro/pamac/commit/dde386ce03500f508e086e9b9d92a541e8b5baa3

**Comment by karasu** [comment] 2018-02-03 18:14
Thanks @philmmanjaro for taking the time to comment here.
I've just seen you have released a new version:
https://github.com/manjaro/pamac/releases/tag/v6.2.4
Thanks!

**Closed** 2018-05-26 13:02 UTC
