### ISSUE TITLE
Pacman cannot update due to dependency issues with light-locker-settings and lightdm-webkit2-greeter

### ISSUE THREAD

**Issue by IvantheDugtrio** [Antergos/antergos-packages#96] opened 2016-04-10 06:13 UTC
Description:
Cannot perform sync-refresh-update due to dependency issues with light-locker-settings and lightdm-webkit2-greeter

Additional info:
Antergos Linux release 2015.08 (ISO-Rolling)

Pacman v5.0.1 - libalpm v10.0.1

* Pacman error message:
error: failed to prepare transction (could not satisfy dependencies)
:: light-locker-settings: installing python-gobject (3.20.0-1) breaks dependency 'python-gobject<3.20'
:: lightdm-webkit2-greeter: installing webkit2gtk (2.12.0-2) breaks dependency 'webkit2gtk<2.12'
:: lightdm-webkit2-greeter: installing gtk3 (3.20.2-1) breaks dependency 'gtk3<3.20'

Steps to reproduce:
sudo pacman -Syu

**Comment by tuxayo** [comment] 2016-04-10 07:22
Duplicate of #94
It's fixed and we are waiting for the mirrors to update.

**Closed** 2016-04-10 18:45 UTC
